version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}

    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
