version: '3'
services:
  app:
    user: '1000:1000'

    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/src
      - ./node_modules:/node_modules
    networks:
      - app-net
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}

    volumes:
      - local_pgdata:/var/lib/postgresql/data

    networks:
      - app-net

volumes:
  local_pgdata:

networks:
  app-net:
