db:
  username: postgres
  password: postgres
  type: postgres
  port: 5432
  dbName: dev_db
  synchronize: true

app:
  port: 3000
  NODE_ENV: development

cors:
  allowedOrigins: localhost
  methods: GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS
  allowedHeaders: Content-Type, Accept, Origin, Access-Control-Allow-Headers

jwt:
  secret: secret
  expiresIn: 2592000
  defaultStrategy: jwt
